### ISSUE TITLE
training difference of two checkpoints

### ISSUE THREAD

**Issue by hw-liang** [alibaba/VideoMV#1]
Hi, this is a great work! We unzip the pretrained_models and found two similar checkpoints:

a) pretrained_models/i2v_882000.pth 
b)pretrained_models/modelscope_i2v/I2VGen-XL/i2vgen_xl_00854500.pth

May I know the training/performance difference btw these two checkpoints?

**Comment by hitsz-zuoqi** [comment]
b) is the original weight of image-to-video diffusion model 
a) is our multi-view fintuned weight on GObjaverse
it means that you should load b) and fintune it, then you get a)
